# Assignment 1

1. Create a 4x4 matrix with values ranging from 0 to 3.\ (The following image is just as an example. It doesn't represent the real image of arrays in the question) 
![](image/assignment2.png)

In [29]:
import numpy as np
from numpy import random

In [18]:
b= np.zeros((4,4))
b[::] = np.arange(4) #mengubah matriks
b

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [20]:
#atau cara lain
a= np.zeros((4,4))
a +=np.arange(4)
a

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.\
![](image/assignment.png)

In [5]:
c = np.arange(0,16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
c2= np.hsplit( c, 2)
c2

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

3. soal tambahan:

misalkan kita memiliki data array seperti berikut ini :

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
       
tuliskan proses filtering untuk mendapatkan hanya elemen data yang berupa bilangan prima ? 

jika dilihat dari data, output yang diinginkan : 2, 3, 7, 11, 13, 17, 19, 23

In [31]:
d= np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
d.shape

(5L, 5L)

In [36]:
def is_prime(n):
    if n == 1:
        return False
    if n == 2:
        return True
    for i in range (2,n):
        if n % i == 0:
            return False
    return True


In [40]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [42]:
prima = []
for line in a: #untuk baris pertama
    for item in line: #untuk lanjut ke baris2lain
        if is_prime(item):
            prima.append(item)
prima

[2, 3, 5, 7, 11, 13, 17, 19, 23]

In [48]:
z=np.array(prima) #untuk membentuk array kembali
z.reshape(3,3)

array([[ 2,  3,  5],
       [ 7, 11, 13],
       [17, 19, 23]])

In [47]:
#cara lain
c=np.array([item for item in a.flatten() if is_prime(item)])
#karna ad flaten 2D telah menjadi 1D, sehingga hantya tinggal item
c

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23])