#  Exercise 4

1. create a null vector / 1D array of size 10 and update fifth value to 11.

In [1]:
import numpy as np

In [5]:
a = np.zeros(10)

In [6]:
a.size

10

In [7]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
a[4]=11

In [9]:
a

array([ 0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.,  0.])

2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

In [12]:
b=np.zeros((2,3))

In [13]:
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
b=b.reshape(3,2)
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [18]:
b.shape

(3L, 2L)

3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.
![](image/lat1.png)

In [19]:
c=np.ones((5,5))
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
c[1:4,1:4]=0

In [24]:
c

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

4. Take a look at the following matrix. access item 99

In [25]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 99, 9],
               [1, 3, 3]]])

In [26]:
#access item 99
z[2,1,1]

99