# Exercise 1

1. Create a matrix from a list which has 4 rows and 3 columns

In [1]:
import numpy as np

In [3]:
n1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
n1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
n1.shape

(4L, 3L)

2. Create the following matrix

In [9]:
n2 = np.array([[2, 7, 12, 0],
               [3, 9, 3, 4],
               [4, 0, 1, 3]])

n2

array([[ 2,  7, 12,  0],
       [ 3,  9,  3,  4],
       [ 4,  0,  1,  3]])

In [ ]:
brs, klm = n2.shape
for i in range(0, brs):
    for j in range(0, klm):
        print(f'{n2[i, j]:2} ', end='')
    print()

In [10]:
n2.shape

(3L, 4L)

In [11]:
n2.size

12

3.Create a 2D matrix with size of 10

In [12]:
n3 =np.array([1,2,3,4,5,6,7,8,9,10])

In [13]:
n3.size


10

In [14]:
n4= np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [15]:
n4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
n4.size

10

In [17]:
n5= np.zeros(10)

In [18]:
n5
n5.size

10

In [19]:
n5

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
n6 = np.ones((2,5)) #baris, kolom
n6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
n6.size

10

4.Create a 3D matrix of ones which has 2 rows, 3 columns, and 3 depth

In [26]:
n7 = np.zeros((2,3,3))#baris, kolom,dalam
n7

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
n7.shape

(2L, 3L, 3L)

In [31]:
n8 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]]])
n8

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [32]:
n8.shape

(2L, 3L, 3L)

5.Make the following arrays from zeros arrays and with for loops

In [33]:
n9 = np.zeros((5,3))

In [34]:
n9

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
for line in n9:
    print(line +2)

[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]
[2. 2. 2.]


### Using array-generating functions

arange

In [37]:
x = np.arange(10)

In [38]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [41]:
# create a range

x = np.arange(10,20,2) #mulai,akhir, jarak

x

array([10, 12, 14, 16, 18])

### Linspace 

In [46]:
# using linspace, both end points ARE included
np.linspace(0, 10, 10) #Unlike arange that uses step, linspace uses the number of sample

array([ 0.        ,  1.22222222,  2.44444444,  3.66666667,  4.88888889,
        6.11111111,  7.33333333,  8.55555556,  9.77777778, 11.        ])

In [49]:
np.linspace(1,10,4)# mulai(termasuk 1) , akhir(termasuk10), banyak angka/space

array([ 1.,  4.,  7., 10.])

### random data 

In [50]:
from numpy import random

In [51]:
random.rand(5,5) #baris, kolom

array([[0.63630249, 0.12094869, 0.05430826, 0.81285312, 0.44838633],
       [0.93252922, 0.11139515, 0.85121223, 0.46533469, 0.0245048 ],
       [0.42031298, 0.86325747, 0.62962856, 0.73854891, 0.51268034],
       [0.79693117, 0.77016795, 0.52127487, 0.50385617, 0.59506381],
       [0.60401095, 0.3193427 , 0.11362172, 0.67583137, 0.38075558]])

In [52]:
x = random.randn(5,5) #random ada yang negatif
x 

array([[-1.32598742,  1.79573348, -0.61473664, -1.67695588,  0.33296025],
       [ 0.2233633 , -0.52019717, -2.02563967, -0.24959526, -1.48769735],
       [ 1.02872555,  1.00120231, -0.21543686,  0.16061846, -0.44531793],
       [-0.32553893, -0.25907204,  0.40963337,  0.39253669, -0.49166583],
       [ 0.64806997, -0.17685798, -1.17683559, -0.81710682,  0.46923408]])

In [53]:
x.dtype #tipe

dtype('float64')

In [56]:
x = np.ones(2, dtype = np.int64) #array dengan matriks 1D dengan type integer

In [57]:
x

array([1, 1], dtype=int64)

In [59]:
#bisa ditulis juga
random.randint(10)

7

In [60]:
random.randint(2,10, size =4) #awal,akhir , sebanyak

array([2, 8, 9, 2])

In [64]:
d= random.randint(2,10, size=(4,2,2))
#random angka 2 sampai 10 dengan ukuran baris 4, kolom 2 dan dalam 2
d

array([[[8, 2],
        [7, 9]],

       [[8, 9],
        [7, 9]],

       [[4, 8],
        [3, 2]],

       [[9, 8],
        [2, 3]]])

In [63]:
d.shape

(4L, 2L, 2L)

# Exercise 2

1. Generate a 1-D array containing 5 random integers from 0 to 100:

In [85]:
contoh1 =random.randint(0,101, size =5)
contoh1

array([52, 82, 66, 76,  2])

2. Generate a 2-D array with 3 rows, each row contains 5 random integers from 0 to 100

In [81]:
contoh2 = random.randint(0,101, size=(3,3))
contoh2

array([[ 9, 74,  6],
       [40, 63, 24],
       [32,  8, 29]])

In [83]:
contoh2.shape

(3L, 3L)

3. Generate a 1-D array of 30 evenly spaced elements between 1.5 and 5.5, inclusive.

In [84]:
contoh3 = np.linspace(1.5, 5.5, 30)
contoh3

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])