# manipulasi array

In [5]:
import numpy as np

### adding /append 

In [4]:
#append = jika data yang ditambah 1

my_arr= np.arange(10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.append(my_arr,10) #bersifat sementara jika setelah ini di panggi my _arr jdi semula

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.append(my_arr,(11,12,13)) #jika tambah beberapa tambah sebagai tupple/list


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [16]:
my_arr1=np.array([[1,2,3],
             [2,4,6]])
my_arr1

array([[1, 2, 3],
       [2, 4, 6]])

In [18]:
#axis 1d hanya ada 1, 2d ada 2 axis (axis =0 dan axis =1), dst


In [17]:
np.append(my_arr1,[[2,1,1]])

array([1, 2, 3, 2, 4, 6, 2, 1, 1])

#create tupple lebih hemat daripda list

In [25]:
a = np.array([[1,2,6],[3,4,5]])
b = np.array([[8,2,1],[3,9,1]])
c = np.concatenate((a,b), axis=0)
#axis=0 diurutkan per baris
print(c)

[[1 2 6]
 [3 4 5]
 [8 2 1]
 [3 9 1]]


In [21]:
c.shape

(4L, 3L)

In [22]:
a = np.array([[1,2,6],[3,4,5]])
b = np.array([[8,2,1],[3,9,1]])
c = np.concatenate((a,b), axis=1)
#axis=1 diurutkan per kolom
print(c)

[[1 2 6 8 2 1]
 [3 4 5 3 9 1]]


sorting

In [27]:
arr=np.array([2,1,5,6,4])
arr


array([2, 1, 5, 6, 4])

In [28]:
np.sort(arr) #urut sementara dari kecil ke besar

array([1, 2, 4, 5, 6])

In [29]:
arr

array([2, 1, 5, 6, 4])

In [33]:
arr.sort() #mengurutkan secara permanen

In [34]:
arr

array([1, 2, 4, 5, 6])

In [19]:
np.sort(arr) #info shift+tab

array([1, 2, 4, 5, 6])

In [36]:
#concatente arrays

a=np.array([1,2,3,4])
b=np.array([5,6,7,8])


In [37]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
np.concatenate((x,y)).shape

(3L, 2L)

# delete element of an array

In [53]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
arr = np.delete(arr,1,axis=1) # pada array, urutan dari 0, baris/kolom)
arr

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [54]:
arr = np.delete(arr,1,axis=1) # pada array, urutan dari 0, barais/kolom)

In [55]:
arr

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

# Shape and Size of an array 

In [56]:
my_array = np.array([[[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                          
                      [[0, 1, 2, 3],
                      [4, 5, 6, 7]],
                         
                      [[0 ,1 ,2, 3],
                      [4, 5, 6, 7]]])

In [57]:
my_array

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [58]:
my_array.shape

(3L, 2L, 4L)

In [59]:
my_array.ndim

3

In [62]:
a=np.arange(1,11)

a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
a.ndim

1

In [65]:
from numpy import random

In [66]:
b=random.randint(1,11, size=(2,5))
b

array([[ 9,  5,  4,  4,  9],
       [ 3, 10,  9,  1, 10]])

In [69]:
b.shape


(2L, 5L)

In [70]:
b.ndim

2

## Reshaping an array

In [25]:
#reshape 
#jumlah element dari properti harus sama

In [71]:
a= np.arange(6)

In [72]:
a


array([0, 1, 2, 3, 4, 5])

In [73]:
a=a.reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [74]:
a.shape

(3L, 2L)

# Exercise 3

1.create a 3x3 matrix with values ranging from 2 to 10

In [6]:
a=np.arange(2,11)
a


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
a=a.reshape(3,3)
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [8]:
#cara langsung
a=np.arange(2,11).reshape(3,3)
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [9]:
a.flatten() #mengembalikan array dalam bentuk 1D
#atau bisa pakai ravel

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
a=a.ravel()
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

2. concentenate the following arrays \
**[[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]**
![](image/lat3.png)

In [13]:
a= np.array([[0,1,3],[5,7,9]])
b=np.array([[0,2,4],[6,8,10]])
print(a)
print(b)

[[0 1 3]
 [5 7 9]]
[[ 0  2  4]
 [ 6  8 10]]


In [14]:
c= np.concatenate((a,b),axis=1) # 0 secara bari, 1 secara kolom
c

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

## Converting a 1D array to into 2D array

#menggunakan newaxis , cara lain seperti reshape

In [15]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6L,)

In [17]:
a2=a[np.newaxis,:]
a2


array([[1, 2, 3, 4, 5, 6]])

In [18]:
a3=a[:,np.newaxis]
a3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [19]:
a3.shape

(6L, 1L)

In [20]:
a

array([1, 2, 3, 4, 5, 6])

using np.expand_dims

In [21]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6L,)

In [22]:
# You can use np.expand_dims to add an axis at index position 1
b = np.expand_dims(a, axis=1)
b.shape

(6L, 1L)

In [23]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [25]:
# You can use np.expand_dims to add an axis at index position 1
c = np.expand_dims(a, axis=0)
c.shape

(1L, 6L)

In [26]:
c

array([[1, 2, 3, 4, 5, 6]])

# indexing and slicing

In [47]:
data = np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [48]:
data

array([1, 2, 3, 4, 5])

In [49]:
data[1] #indeks terkecil dari 0

2

In [51]:
data[:3] #mulai dari indeks 0,1,2 dan berhenti sebelum 3

array([1, 2])

In [53]:
#slicing [m:n:s]
#m bersifat incllude, n exclude

In [54]:
data[-2:] #dari 2 terakhir

array([4, 5])

In [58]:
data[::2]

array([1, 3, 5])

In [59]:
data = np.arange (1,26).reshape(5,5)

In [60]:
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [65]:
data[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [67]:
data[:2,:2]

array([[1, 2],
       [6, 7]])

In [68]:
data[-2:,-2:]

array([[19, 20],
       [24, 25]])

In [75]:
data[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [77]:
data[0,0]=0 #mengubah data
data

array([[ 0,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [78]:
data[1:4 ,1:4]=0

In [79]:
data

array([[ 0,  2,  3,  4,  5],
       [ 6,  0,  0,  0, 10],
       [11,  0,  0,  0, 15],
       [16,  0,  0,  0, 20],
       [21, 22, 23, 24, 25]])

In [28]:
a = np.array([[1 , 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
print (a[a<5]) #print pada matriks a dengan nilai yang kecil dari 5

[1 2 3 4]


In [30]:
a>=5 #mengecek a besar dari 5 yang mana 

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [31]:
five_up =(a>=5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [32]:
#yang bisa dibagi 2
divisible_by_2 =a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [33]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [34]:
# pipe, or, vertical bar: |
five_up = (a > 5) | (a == 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [35]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
a[1,1:3]

array([6, 7])

In [82]:
a=np.arange(0,13).reshape(3,4)

ValueError: cannot reshape array of size 13 into shape (3,4)

In [84]:
a = np.arange (1,13).reshape(3,4)

In [85]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
b=np.arange(11)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
#membalikkan 
b[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [94]:
#jika numpy pakai & bukan and(pakai simbol)

In [101]:
c=np.zeros(11)

In [102]:
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [103]:
c[4]=11

In [104]:
c

array([ 0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.,  0.,  0.])

In [108]:
d=np.arange(1,7).reshape(2,3)

In [109]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
d=d.reshape(3,2)

In [112]:
d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [113]:
d.shape

(3L, 2L)

In [114]:
#3

In [119]:
e=np.ones((5,5)) #banyak kurung mempengaruhi dimensi matriks
e

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [121]:
e[1:4,1:4]=0
e

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# creating

In [122]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [123]:
arr1=a[3:8]

In [124]:
arr1

array([4, 5, 6, 7, 8])

In [125]:
#stacking array
a1 = np

###Split 

In [127]:
x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [128]:
y=np.hsplit(x,(3,5))
y

[array([[ 1,  2,  3],
        [13, 14, 15]]), array([[ 4,  5],
        [16, 17]]), array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24]])]

# broadcasting

In [ ]:
data